name: Story
description: User story that describes a new feature or improvement
labels: story
body:
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
    validations:
      required: true
