name: Story
about: User story that describes a new feature or improvement
title: ''
labels: story
assignees: ''
body:
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Whenever I visit the user account page (1-2 times a week)"
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
    validations:
      required: true
